version: '3'
services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    build: 
      context: ./db
    image: oakel/adl-db
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: 
      context: ./app
    image: oakel/adl-app
    ports:
     - 80:80
    environment:
     - DATABASE_HOST=db
     - WAIT_HOSTS=db:3306
    depends_on: 
      - db
 